// Generated by CoffeeScript 1.6.3
(function() {
  Polymer('yo-player', {
    play: function(toPlay) {
      var _this;
      _this = this;
      return $.post('/searchTrack', {
        toPlay: toPlay
      }, function(res) {
        var code;
        code = res.url.split('v=')[1].split('&')[0];
        _this.active = true;
        return _this.url = "https://www.youtube.com/embed/" + code + "?autoplay=1";
      });
    },
    ready: function() {
      this.title = '';
      this.active = false;
      this.loading = true;
      this.state = 0;
      this.items = [];
      return this.toPlay = _.debounce(this.getToPlay, 1000);
    },
    getTracks: function(id, href) {
      var _this;
      _this = this;
      setTimeout(function() {
        $(window).scrollTop(0);
        return _this.active = true;
      }, 350);
      return $.get("/playlists/" + id + "/tracks", {
        href: href
      }, function(res) {
        _this.loading = false;
        return _this.items = res.items;
      });
    },
    playFirst: function() {
      if (this.state === 1) {
        return;
      }
      this.state = 1;
      console.log('here');
      return this.play(this.items[0]);
    },
    close: function() {
      return this.active = false;
    }
  });

}).call(this);
